# This workflow will build a package using Gradle.
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build master branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 8
    - name: Print version
      run: gradle printVersion
    - name: Build with Gradle
      run: gradle build
    - name: Generate sources jar with Gradle
      run: gradle sourcesjar
    - name: Generate JavaDoc jar with Gradle
      run: gradle javadocjar
    - name: Upload package as artifact
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: build/libs
